---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  labels:
    app: HttpSample.application
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: com.tibco.bw
  name: default
  namespace: default
status:
  phase: Active
