---
apiVersion: v1
kind: List
items:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    labels:
      app: HttpSample.application
      provider: fabric8
      version: 1.0.0-SNAPSHOT
      group: com.tibco.bw
    name: default
    namespace: default
  status:
    phase: Active
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      container: bwce-sample
      provider: fabric8
      project: bwce-sample
      group: com.tibco.bw
      expose: "true"
      app: HttpSample.application
      version: 1.0.0-SNAPSHOT
    name: bwce-sample-service
    namespace: default
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      container: bwce-sample
      provider: fabric8
      project: bwce-sample
      group: com.tibco.bw
      app: HttpSample.application
    type: NodePort
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: HttpSample.application
      provider: fabric8
      version: 1.0.0-SNAPSHOT
      group: com.tibco.bw
    name: bwce-sample
    namespace: default
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: HttpSample.application
      provider: fabric8
      group: com.tibco.bw
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        labels:
          container: bwce-sample
          project: bwce-sample
          app: HttpSample.application
          provider: fabric8
          version: 1.0.0-SNAPSHOT
          group: com.tibco.bw
        name: bwce-sample
        namespace: default
      spec:
        containers:
        - image: localhost:5000/httpsample
          imagePullPolicy: Always
          name: bwce-sample
          ports:
          - containerPort: 8080
            name: http
    triggers:
    - type: ConfigChange
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      container: bwce-sample
      provider: fabric8
      project: bwce-sample
      group: com.tibco.bw
      app: HttpSample.application
      version: 1.0.0-SNAPSHOT
    name: bwce-sample-service
    namespace: default
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: bwce-sample-service
